SOURCES := SerialGateway.cpp
TARGET := SerialGateway
BOARD := pro328
LIBRARIES := MySensors SPI Mqtt
SERIALDEV := /dev/ttyUSB0
MONITORSPEED := 9600
include ../arduino.mk
LIBRARYPATH := $(ARDUINODIR)/libraries ../Arduino/libraries/
