SOURCES := HumiditySensor.cpp
TARGET := HumiditySensor
BOARD := pro328
LIBRARIES := MySensors SPI DHT
SERIALDEV := /dev/ttyUSB0
MONITORSPEED := 9600
include ../arduino.mk
LIBRARYPATH := $(ARDUINODIR)/libraries ../Arduino/libraries/
